#!/bin/bash
# meant to be run on login
# checks to make sure there is a /tmp/powerd file, then waits for writes to
# it. reads the file, and does what the file says.
name=$(basename "$0")
if [ ! -f /tmp/powerd ]; then
    touch /tmp/powerd || ((>&2 echo "$name can't make /tmp/powerd") && exit 1)
fi
while true; do
    if inotifywait -e modify /tmp/powerd; then
        trigger=$(cat /tmp/powerd)
        rm /tmp/powerd
        case "$trigger" in
            poweroff) echo "poweroff"; break;;
            reboot) echo "reboot"; break;;
            *) echo "not a cmd"; touch /tmp/powerd;;
        esac
    fi
done
